version: 2.1

executors:
  nodejs-browsers:
    docker:
      - image: circleci/node:12.19.0-browsers
  nodejs:
    docker:
      - image: circleci/node:12.19

jobs:
  test-ballot-encoder:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/ballot-encoder lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir libs/ballot-encoder test:coverage

  test-bas:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/bas lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir apps/bas test:coverage

  test-bmd:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/bmd lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir apps/bmd test:coverage

  test-bsd:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/bsd lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir apps/bsd test:coverage

  test-election-manager:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/election-manager lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir apps/election-manager test:coverage

  test-fixtures:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/fixtures lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir libs/fixtures test:coverage

  test-hmpb-interpreter:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/hmpb-interpreter lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir libs/hmpb-interpreter test:coverage

  test-lsd:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Build
          command: |
            pnpm --dir libs/lsd build
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/lsd lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir libs/lsd test:coverage

  test-module-scan:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/module-scan lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir apps/module-scan test:coverage

  test-module-smartcards:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Set up python tools for backend
          command: |
            sudo apt update -y
            make -C apps/module-smartcards install-smartcard
            make -C apps/module-smartcards build-dev
      - run:
          name: Run Python Tests and Coverage
          command: |
            make -C apps/module-smartcards coverage
      - run:
          name: Run Mypy Type Checking
          command: |
            make -C apps/module-smartcards typecheck

  test-plustek-sdk:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Build
          command: |
            pnpm --dir libs/plustek-sdk build
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/plustek-sdk lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir libs/plustek-sdk test:coverage

  test-precinct-scanner:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir apps/precinct-scanner lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir apps/precinct-scanner test:coverage

  test-types:
    executor: nodejs
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/types lint
      - run:
          name: Run Tests with Coverage
          command: |
            pnpm --dir libs/types test:coverage

  test-ui:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/ui lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir libs/ui test:coverage

  test-utils:
    executor: nodejs-browsers
    resource_class: xlarge
    steps:
      - checkout-and-install
      - run:
          name: Build
          command: |
            pnpm --dir /libs/utils build
      - run:
          name: Run Linters
          command: |
            pnpm --dir libs/utils lint
      - run:
          name: Run Front-End Test and Coverage
          command: |
            pnpm --dir libs/utils test:coverage

workflows:
  test:
    jobs:
      - test-ballot-encoder
      - test-bas
      - test-bmd
      - test-bsd
      - test-election-manager
      - test-fixtures
      - test-hmpb-interpreter
      - test-lsd
      - test-module-scan
      - test-module-smartcards
      - test-plustek-sdk
      - test-precinct-scanner
      - test-types
      - test-ui
      - test-utils

commands:
  checkout-and-install:
    description: Get the code and install dependencies.
    steps:
      - run:
          name: Install pnpm
          command: |
            curl -f https://get.pnpm.io/v6.js | sudo node - add --global pnpm@5
      - checkout
      # Edit this comment somehow in order to invalidate the CircleCI cache.
      # Since the contents of this file affect the cache key, editing only a
      # comment will invalidate the cache without changing the behavior.
      - restore_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "pnpm-lock.yaml" }}
      - run:
          name: Setup Dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
